# Site settings
title: The Dean Lab
email: tom@codegaucho.com
description: > # this means to ignore newlines until "baseurl:"
  This is The Dean Lab, a nanoelectronics laboratory out of Columbia University.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://deanlab.github.io" # the base hostname & protocol for your site
twitter_username: codegaucho
github_username:  deanlab
cloudinary_id: codegaucho

collections:
  research:
    output: true
  people:
    output: true
  equipment:
    output: true

defaults:
  -
    scope:
      type: research
    values:
      layout: research
      image_options: "c_scale,w_320"
      thumbnail_options: "c_scale,w_256"
      active_nav: Research
  -
    scope:
      type: people
    values:
      layout: people
      image_options: "c_scale,w_320"
      thumbnail_options: "c_crop,h_200,w_246"
      active_nav: People
  -
    scope:
      type: equipment
    values:
      layout: equipment
      image_options: "c_scale,w_320"
      thumbnail_options: "c_scale,w_256"
      active_nav: Equipment

# Build settings
markdown: kramdown
