# Site settings
title: The Dean Lab
email: cory.dean@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is The Dean Lab, a nanoelectronics laboratory out of Columbia University.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://deanlab.github.io" # the base hostname & protocol for your site
# twitter_username: codegaucho
github_username:  deanlab
cloudinary_id: codegaucho
google_plus: 107324455351703736624
google_scholar: z3z-PV8AAAAJ
freefind: 72794858

collections:
  navpages:
    output: true
  research:
    output: true
  people:
    output: true
  equipment:
    output: true
  news:
    output: true

defaults:
  -
    scope:
      category: feature
    values:
      feature_options: "c_scale,w_320"
  -
    scope:
      type: navpages
    values:
      layout: page
  -
    scope:
      type: research
    values:
      layout: research
      image_options: "c_scale,w_320"
      thumbnail_options: "c_scale,w_256"
      active_nav: Research
  -
    scope:
      type: people
    values:
      layout: people
      image_options: "c_scale,w_320"
      thumbnail_options: "c_crop,h_200,w_246"
      active_nav: People
  -
    scope:
      type: equipment
    values:
      layout: equipment
      image_options: "c_scale,w_320"
      thumbnail_options: "c_scale,w_256"
      active_nav: Equipment
  -
    scope:
      type: news
    values:
      layout: news
      image_options: "c_scale,w_320"
      thumbnail_options: "c_scale,w_256"
      active_nav: News

# Build settings
markdown: kramdown
